/* The following code was generated by JFlex 1.6.1 */

//packages
package minicsharp;
import java.util.ArrayList;
import java.io.FileWriter;
import java.io.IOException;
import java_cup.runtime.Symbol;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>miniCsharp.jflex</tt>
 */
public class Analyzer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\36\1\34\1\36\1\36\1\36\22\0\1\36\1\3\1\33"+
    "\2\0\1\7\1\10\1\0\1\67\1\70\1\5\1\4\1\75\1\12"+
    "\1\31\1\6\1\25\7\14\2\14\1\0\1\66\1\1\1\2\1\1"+
    "\2\0\1\55\1\65\2\30\1\32\1\30\1\64\1\13\1\61\2\13"+
    "\1\62\1\63\1\54\1\13\1\57\1\13\1\60\5\13\1\27\2\13"+
    "\1\71\1\35\1\72\1\0\1\13\1\0\1\22\1\46\1\50\1\43"+
    "\1\20\1\21\1\47\1\51\1\37\1\13\1\53\1\23\1\40\1\42"+
    "\1\45\1\41\1\13\1\16\1\24\1\15\1\17\1\44\1\52\1\26"+
    "\1\56\1\13\1\73\1\11\1\74\1\0\6\13\1\13\32\13\1\13"+
    "\137\13\u1580\0\1\36\u097f\0\13\36\35\0\1\36\1\36\5\0\1\36"+
    "\57\0\1\36\u0fa0\0\1\36\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\ud00f\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\3\5\1\1\1\6"+
    "\1\7\1\10\1\11\5\10\1\11\1\12\1\1\1\13"+
    "\1\6\14\10\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\2\1\3\1\24\1\0\1\25\1\26"+
    "\7\10\2\0\1\27\1\0\1\30\16\10\1\31\1\24"+
    "\2\0\1\32\4\26\7\10\1\11\1\27\1\10\1\33"+
    "\7\10\1\34\4\10\1\24\1\35\2\0\1\26\1\0"+
    "\1\36\1\37\1\10\1\40\4\10\1\41\1\10\1\42"+
    "\1\10\1\43\7\10\1\35\1\0\1\26\6\10\1\44"+
    "\1\45\1\46\1\10\1\47\4\10\1\24\2\26\1\50"+
    "\1\10\1\51\2\10\1\52\3\10\1\53\1\10\1\24"+
    "\2\0\1\26\1\54\5\10\1\55\2\10\1\56\1\10"+
    "\1\57\1\10\1\60\1\10\1\61\1\10\1\62";

  private static int [] zzUnpackAction() {
    int [] result = new int[187];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\76\0\174\0\174\0\174\0\272\0\370\0\76"+
    "\0\u0136\0\u0174\0\272\0\u01b2\0\u01f0\0\u022e\0\u026c\0\u02aa"+
    "\0\u02e8\0\u0326\0\u0364\0\76\0\u03a2\0\76\0\76\0\u03e0"+
    "\0\u041e\0\u045c\0\u049a\0\u04d8\0\u0516\0\u0554\0\u0592\0\u05d0"+
    "\0\u060e\0\u064c\0\u068a\0\76\0\76\0\76\0\u06c8\0\76"+
    "\0\76\0\76\0\76\0\76\0\76\0\u0706\0\u0744\0\76"+
    "\0\u0782\0\u07c0\0\u07fe\0\u083c\0\u087a\0\u08b8\0\u08f6\0\u0934"+
    "\0\u0972\0\u03a2\0\76\0\u09b0\0\u01b2\0\u09ee\0\u0a2c\0\u0a6a"+
    "\0\u0aa8\0\u0ae6\0\u0b24\0\u0b62\0\u0ba0\0\u0bde\0\u0c1c\0\u0c5a"+
    "\0\u0c98\0\u0cd6\0\u0d14\0\76\0\u0d52\0\u0d90\0\u0dce\0\76"+
    "\0\u0e0c\0\u0e4a\0\u0e88\0\u0ec6\0\u0f04\0\u0f42\0\u0f80\0\u0fbe"+
    "\0\u0ffc\0\u103a\0\u1078\0\u0972\0\u03a2\0\u10b6\0\u10f4\0\u1132"+
    "\0\u1170\0\u11ae\0\u11ec\0\u122a\0\u1268\0\u12a6\0\u12e4\0\u1322"+
    "\0\u1360\0\u139e\0\u13dc\0\u141a\0\76\0\u1458\0\u1496\0\u14d4"+
    "\0\u1512\0\u01b2\0\u01b2\0\u1550\0\u01b2\0\u158e\0\u15cc\0\u160a"+
    "\0\u1648\0\u01b2\0\u1686\0\u01b2\0\u16c4\0\u01b2\0\u1702\0\u1740"+
    "\0\u177e\0\u17bc\0\u17fa\0\u1838\0\u1876\0\u18b4\0\u18f2\0\u1930"+
    "\0\u196e\0\u19ac\0\u19ea\0\u1a28\0\u1a66\0\u1aa4\0\u01b2\0\u01b2"+
    "\0\u01b2\0\u1ae2\0\u01b2\0\u1b20\0\u1b5e\0\u1b9c\0\u1bda\0\u1c18"+
    "\0\u1c56\0\u1c94\0\u01b2\0\u1cd2\0\u01b2\0\u1d10\0\u1d4e\0\u01b2"+
    "\0\u1d8c\0\u1dca\0\u1e08\0\u01b2\0\u1e46\0\u1e84\0\u1ec2\0\u18b4"+
    "\0\u1f00\0\u01b2\0\u1f3e\0\u1f7c\0\u1fba\0\u1ff8\0\u2036\0\u01b2"+
    "\0\u2074\0\u20b2\0\u01b2\0\u20f0\0\u01b2\0\u212e\0\u01b2\0\u216c"+
    "\0\u01b2\0\u21aa\0\u01b2";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[187];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\2\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\14\1\20"+
    "\1\21\2\14\1\22\1\23\3\14\1\24\1\14\1\25"+
    "\1\26\1\2\1\27\1\30\2\14\1\31\1\32\1\33"+
    "\1\14\1\34\1\14\1\35\1\14\1\36\1\14\1\37"+
    "\2\14\1\40\1\41\2\14\1\42\1\43\1\14\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\53\100\0"+
    "\1\54\75\0\1\55\100\0\1\56\1\57\77\0\1\60"+
    "\76\0\1\60\77\0\16\14\1\0\1\14\4\0\27\14"+
    "\24\0\1\15\10\0\1\15\3\0\1\61\57\0\3\14"+
    "\1\62\12\14\1\0\1\14\4\0\12\14\1\63\14\14"+
    "\23\0\5\14\1\64\10\14\1\0\1\14\4\0\27\14"+
    "\23\0\10\14\1\65\2\14\1\66\2\14\1\0\1\14"+
    "\4\0\27\14\23\0\7\14\1\67\6\14\1\0\1\14"+
    "\4\0\27\14\23\0\2\14\1\70\13\14\1\0\1\14"+
    "\4\0\27\14\24\0\1\15\10\0\1\15\2\71\1\0"+
    "\1\61\44\0\33\72\1\73\1\0\1\74\40\72\13\0"+
    "\6\14\1\75\7\14\1\0\1\14\4\0\1\14\1\76"+
    "\1\14\1\77\23\14\23\0\4\14\1\100\11\14\1\0"+
    "\1\14\4\0\27\14\23\0\16\14\1\0\1\14\4\0"+
    "\6\14\1\101\20\14\23\0\16\14\1\0\1\14\4\0"+
    "\6\14\1\102\20\14\23\0\3\14\1\103\12\14\1\0"+
    "\1\14\4\0\6\14\1\104\20\14\23\0\10\14\1\105"+
    "\5\14\1\0\1\14\4\0\27\14\23\0\16\14\1\0"+
    "\1\14\4\0\12\14\1\106\14\14\23\0\5\14\1\107"+
    "\10\14\1\0\1\14\4\0\27\14\23\0\3\14\1\110"+
    "\12\14\1\0\1\14\4\0\27\14\23\0\5\14\1\111"+
    "\10\14\1\0\1\14\4\0\27\14\23\0\7\14\1\112"+
    "\6\14\1\0\1\14\4\0\27\14\23\0\5\14\1\113"+
    "\10\14\1\0\1\14\4\0\27\14\102\0\1\114\3\0"+
    "\5\115\1\116\1\117\67\115\34\57\1\120\41\57\4\0"+
    "\1\121\5\0\1\121\1\0\1\61\3\0\1\122\4\0"+
    "\1\123\3\0\1\124\1\122\56\0\4\14\1\125\11\14"+
    "\1\0\1\14\4\0\27\14\23\0\16\14\1\0\1\14"+
    "\4\0\1\126\26\14\23\0\2\14\1\127\13\14\1\0"+
    "\1\14\4\0\27\14\23\0\11\14\1\130\4\14\1\0"+
    "\1\14\4\0\27\14\23\0\2\14\1\131\13\14\1\0"+
    "\1\14\4\0\27\14\23\0\10\14\1\132\5\14\1\0"+
    "\1\14\4\0\27\14\23\0\3\14\1\133\12\14\1\0"+
    "\1\14\4\0\27\14\24\0\1\134\3\0\3\134\2\0"+
    "\1\134\2\0\1\134\1\0\1\134\10\0\1\134\2\0"+
    "\1\134\1\0\1\134\4\0\1\134\7\0\1\134\10\0"+
    "\33\72\1\135\1\0\1\74\40\72\13\0\16\14\1\0"+
    "\1\14\4\0\2\14\1\136\24\14\23\0\2\14\1\137"+
    "\13\14\1\0\1\14\4\0\27\14\23\0\10\14\1\140"+
    "\5\14\1\0\1\14\4\0\27\14\23\0\4\14\1\141"+
    "\11\14\1\0\1\14\4\0\27\14\23\0\16\14\1\0"+
    "\1\14\4\0\1\142\26\14\23\0\5\14\1\143\10\14"+
    "\1\0\1\14\4\0\27\14\23\0\16\14\1\0\1\14"+
    "\4\0\6\14\1\144\20\14\23\0\7\14\1\145\6\14"+
    "\1\0\1\14\4\0\27\14\23\0\16\14\1\0\1\14"+
    "\4\0\1\146\26\14\23\0\16\14\1\0\1\14\4\0"+
    "\13\14\1\147\13\14\23\0\16\14\1\0\1\14\4\0"+
    "\1\150\26\14\23\0\7\14\1\151\6\14\1\0\1\14"+
    "\4\0\27\14\23\0\10\14\1\152\5\14\1\0\1\14"+
    "\4\0\27\14\23\0\2\14\1\153\13\14\1\0\1\14"+
    "\4\0\27\14\10\0\5\115\1\116\70\115\5\56\1\154"+
    "\1\155\67\56\5\156\1\157\1\56\67\156\14\0\1\121"+
    "\10\0\1\160\3\0\1\124\50\0\1\121\5\0\1\121"+
    "\1\0\1\121\10\0\1\160\3\0\1\124\50\0\1\121"+
    "\5\0\1\121\1\0\1\61\3\0\1\122\4\0\1\123"+
    "\2\161\1\0\1\124\1\122\57\0\1\124\10\0\1\124"+
    "\63\0\5\14\1\162\10\14\1\0\1\14\4\0\27\14"+
    "\23\0\11\14\1\163\4\14\1\0\1\14\4\0\27\14"+
    "\23\0\4\14\1\164\11\14\1\0\1\14\4\0\27\14"+
    "\23\0\5\14\1\165\10\14\1\0\1\14\4\0\27\14"+
    "\23\0\5\14\1\166\10\14\1\0\1\14\4\0\27\14"+
    "\23\0\11\14\1\125\4\14\1\0\1\14\4\0\27\14"+
    "\23\0\16\14\1\0\1\14\4\0\1\167\26\14\23\0"+
    "\10\14\1\170\5\14\1\0\1\14\4\0\27\14\23\0"+
    "\5\14\1\171\10\14\1\0\1\14\4\0\27\14\23\0"+
    "\10\14\1\172\5\14\1\0\1\14\4\0\27\14\23\0"+
    "\16\14\1\0\1\14\4\0\7\14\1\173\17\14\23\0"+
    "\16\14\1\0\1\14\4\0\4\14\1\174\22\14\23\0"+
    "\7\14\1\175\6\14\1\0\1\14\4\0\27\14\23\0"+
    "\10\14\1\176\5\14\1\0\1\14\4\0\27\14\23\0"+
    "\11\14\1\177\4\14\1\0\1\14\4\0\27\14\23\0"+
    "\10\14\1\200\5\14\1\0\1\14\4\0\27\14\23\0"+
    "\16\14\1\0\1\14\4\0\16\14\1\201\10\14\23\0"+
    "\16\14\1\0\1\14\4\0\3\14\1\202\23\14\23\0"+
    "\16\14\1\0\1\14\4\0\4\14\1\203\22\14\23\0"+
    "\10\14\1\204\5\14\1\0\1\14\4\0\27\14\23\0"+
    "\16\14\1\0\1\14\4\0\26\14\1\205\10\0\5\115"+
    "\1\116\1\206\67\115\5\156\1\157\75\156\1\157\1\155"+
    "\67\156\14\0\1\121\10\0\1\160\2\207\1\0\1\124"+
    "\60\0\1\210\3\0\3\210\2\0\1\210\2\0\1\210"+
    "\1\0\1\210\10\0\1\210\2\0\1\210\1\0\1\210"+
    "\4\0\1\210\7\0\1\210\23\0\3\14\1\211\12\14"+
    "\1\0\1\14\4\0\27\14\23\0\16\14\1\0\1\14"+
    "\4\0\3\14\1\212\23\14\23\0\16\14\1\0\1\14"+
    "\4\0\3\14\1\213\23\14\23\0\5\14\1\214\10\14"+
    "\1\0\1\14\4\0\27\14\23\0\3\14\1\215\12\14"+
    "\1\0\1\14\4\0\27\14\23\0\10\14\1\216\5\14"+
    "\1\0\1\14\4\0\27\14\23\0\16\14\1\0\1\14"+
    "\4\0\14\14\1\217\12\14\23\0\11\14\1\220\4\14"+
    "\1\0\1\14\4\0\27\14\23\0\5\14\1\221\10\14"+
    "\1\0\1\14\4\0\27\14\23\0\3\14\1\222\12\14"+
    "\1\0\1\14\4\0\27\14\23\0\2\14\1\223\13\14"+
    "\1\0\1\14\4\0\27\14\23\0\16\14\1\0\1\14"+
    "\4\0\22\14\1\224\1\225\3\14\23\0\16\14\1\0"+
    "\1\14\4\0\6\14\1\226\20\14\23\0\16\14\1\0"+
    "\1\14\4\0\17\14\1\227\7\14\16\0\1\230\103\0"+
    "\1\231\3\0\3\231\2\0\1\231\2\0\1\231\1\0"+
    "\1\231\10\0\1\231\2\0\1\231\1\0\1\231\4\0"+
    "\1\231\7\0\1\231\14\0\1\121\5\0\1\121\1\0"+
    "\1\210\3\0\3\210\2\0\1\232\2\0\1\210\1\124"+
    "\1\210\10\0\1\210\2\0\1\210\1\0\1\210\4\0"+
    "\1\210\7\0\1\210\23\0\16\14\1\0\1\14\4\0"+
    "\3\14\1\233\23\14\23\0\16\14\1\0\1\14\4\0"+
    "\4\14\1\234\22\14\23\0\16\14\1\0\1\14\4\0"+
    "\10\14\1\235\16\14\23\0\16\14\1\0\1\14\4\0"+
    "\1\14\1\236\25\14\23\0\6\14\1\237\7\14\1\0"+
    "\1\14\4\0\27\14\23\0\5\14\1\240\10\14\1\0"+
    "\1\14\4\0\27\14\23\0\3\14\1\241\12\14\1\0"+
    "\1\14\4\0\27\14\23\0\16\14\1\0\1\14\4\0"+
    "\3\14\1\242\23\14\23\0\16\14\1\0\1\14\4\0"+
    "\1\243\26\14\23\0\16\14\1\0\1\14\4\0\11\14"+
    "\1\244\15\14\23\0\2\14\1\245\13\14\1\0\1\14"+
    "\4\0\27\14\10\0\5\246\1\247\1\250\67\246\14\0"+
    "\1\231\3\0\3\231\2\0\1\251\2\0\1\231\1\124"+
    "\1\231\10\0\1\231\2\0\1\231\1\0\1\231\4\0"+
    "\1\231\7\0\1\231\14\0\1\121\5\0\1\121\1\0"+
    "\1\210\3\0\3\210\2\0\1\232\2\161\1\210\1\124"+
    "\1\210\10\0\1\210\2\0\1\210\1\0\1\210\4\0"+
    "\1\210\7\0\1\210\23\0\11\14\1\252\4\14\1\0"+
    "\1\14\4\0\27\14\23\0\5\14\1\253\10\14\1\0"+
    "\1\14\4\0\27\14\23\0\7\14\1\254\6\14\1\0"+
    "\1\14\4\0\27\14\23\0\7\14\1\255\6\14\1\0"+
    "\1\14\4\0\27\14\23\0\2\14\1\256\13\14\1\0"+
    "\1\14\4\0\27\14\23\0\16\14\1\0\1\14\4\0"+
    "\3\14\1\257\23\14\23\0\5\14\1\260\10\14\1\0"+
    "\1\14\4\0\27\14\10\0\5\246\1\247\70\246\6\230"+
    "\1\0\67\230\14\0\1\231\3\0\3\231\2\0\1\251"+
    "\2\207\1\231\1\124\1\231\10\0\1\231\2\0\1\231"+
    "\1\0\1\231\4\0\1\231\7\0\1\231\23\0\16\14"+
    "\1\0\1\14\4\0\3\14\1\261\23\14\23\0\16\14"+
    "\1\0\1\14\4\0\11\14\1\262\15\14\23\0\16\14"+
    "\1\0\1\14\4\0\17\14\1\263\7\14\23\0\5\14"+
    "\1\264\10\14\1\0\1\14\4\0\27\14\23\0\5\14"+
    "\1\265\10\14\1\0\1\14\4\0\27\14\23\0\2\14"+
    "\1\266\13\14\1\0\1\14\4\0\27\14\23\0\5\14"+
    "\1\267\10\14\1\0\1\14\4\0\27\14\23\0\16\14"+
    "\1\0\1\14\4\0\10\14\1\270\16\14\23\0\11\14"+
    "\1\271\4\14\1\0\1\14\4\0\27\14\23\0\5\14"+
    "\1\272\10\14\1\0\1\14\4\0\27\14\23\0\3\14"+
    "\1\273\12\14\1\0\1\14\4\0\27\14\10\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8680];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\1\11\13\1\1\11\1\1\2\11"+
    "\14\1\3\11\1\1\6\11\1\1\1\0\1\11\10\1"+
    "\2\0\1\11\1\0\17\1\1\11\1\1\2\0\1\11"+
    "\34\1\1\11\2\0\1\1\1\0\25\1\1\0\37\1"+
    "\2\0\23\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[187];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
//Developer´s extra code declaration
private Symbol symbol(int type){
	return new Symbol(type,yyline,yycolumn,yytext());
}

private Symbol symbol(int type,Object value){
	return new Symbol(type,yyline,yycolumn,value	);
}
private static int errorCounter=0;
public   boolean commentError=false;
class token{
	public String content="";
	public int line=0;
	public int column=0;
	public token(String aContent,int aLine,int aColumn){
			content=aContent;
			line=aLine;
			column=aColumn;
	}
}
class Yytoken{
		public Yytoken(){

		}
	}
public static ArrayList<String>TokenList=new ArrayList<String>();
private static String  addsTabs(int tokenLength){
	String tabs="";
	for(int i=32-tokenLength;i>0;i--){
		tabs+=" ";
	}
	return tabs;

}
public static String CreateTokenLog(Boolean isError,String token, int lineNumber,int columnNumber,String description){
	String newToken=token+addsTabs(token.length())+"\t\tLine Number: "+(lineNumber+1)+"\t"+"Column Number: "+(columnNumber)+" To: "+getLastColumn(columnNumber,token.length())+"\tToken Type: "+description+" Token: "+token+"\n";

	String ErrorToken=token+addsTabs(token.length())+"\t\tError at line: "+(lineNumber+1)+"\tDescription: "+description+"\n";

	return isError?ErrorToken:newToken;
}
public static int getLastColumn(int firstColumns,int tokenLength){
	return firstColumns+tokenLength;
}
public static void CreateOutputFile(String outputPath) throws IOException{
	FileWriter writer = null; 
      try {
          writer = new FileWriter(outputPath);
      } catch (IOException ex) {
          System.out.println("Something wrong happened with the output file...");
      }
for(String str: TokenList) {
  writer.write(str);
}
writer.close();
System.out.println("Done!");
if(errorCounter==0){
	System.out.println("The file contains no errors, This file is a cs file");
}
else{
	System.out.println("The file contains "+errorCounter+" errors, This is not a cs file");
}
}




  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Analyzer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 242) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { TokenList.add(CreateTokenLog(true,yytext(),yyline,yycolumn,"UNRECOGNIZED CHARACTER")); errorCounter+=1;
				System.out.println("Caracter no reconocido en la linea: "+yyline+" columna: "+yycolumn+" caracter: "+yytext());
            }
          case 51: break;
          case 2: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,yytext()));
							return new Symbol(sym.comp,yycolumn,yyline,yytext());
            }
          case 52: break;
          case 3: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"="));
							return new Symbol(sym.equal,yycolumn,yyline,yytext());
            }
          case 53: break;
          case 4: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"!"));
							return new Symbol(sym.exclamation,yycolumn,yyline,yytext());
            }
          case 54: break;
          case 5: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,yytext()));
							return new Symbol(sym.arit,yycolumn,yyline,yytext());
            }
          case 55: break;
          case 6: 
            { /*TokenList.add(CreateTokenLog(false,yytext(),yyline,yycolumn,"WHITE_SPACE"));*/
            }
          case 56: break;
          case 7: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,yytext()));
							return new Symbol(sym.minus,yycolumn,yyline,yytext());
            }
          case 57: break;
          case 8: 
            { if(yytext().length()>31){
			
							TokenList.add(CreateTokenLog(true,yytext().substring(0,30),yyline,yycolumn,"IDENTIFIER_TO_LONG,_MAX_SIZE_31_CHARACTERS"));
							errorCounter+=1;
						}
						else{
							TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"IDENTIFIER"));
							return new Symbol(sym.IDENT,yycolumn,yyline,"ID");
						}
            }
          case 58: break;
          case 9: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"INTEGER"));
							return new Symbol(sym.INTCONSTANT,yycolumn,yyline,yytext());
            }
          case 59: break;
          case 10: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"."));
						return new Symbol(sym.dot,yycolumn,yyline,yytext());
            }
          case 60: break;
          case 11: 
            { /*Do nothing...*/
            }
          case 61: break;
          case 12: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,";"));
						return new Symbol(sym.semicolon,yycolumn,yyline,yytext());
            }
          case 62: break;
          case 13: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"("));
						return new Symbol(sym.leftparen,yycolumn,yyline,yytext());
            }
          case 63: break;
          case 14: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,")"));
						return new Symbol(sym.rightparen,yycolumn,yyline,yytext());
            }
          case 64: break;
          case 15: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"["));
						return new Symbol(sym.leftsquarebrace,yycolumn,yyline,yytext());
            }
          case 65: break;
          case 16: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"]"));
						return new Symbol(sym.rightsquarebrace,yycolumn,yyline,yytext());
            }
          case 66: break;
          case 17: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"{"));
						return new Symbol(sym.leftbrace,yycolumn,yyline,yytext());
            }
          case 67: break;
          case 18: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"}"));
						return new Symbol(sym.rightbrace,yycolumn,yyline,yytext());
            }
          case 68: break;
          case 19: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,","));
						return new Symbol(sym.comma,yycolumn,yyline,yytext());
            }
          case 69: break;
          case 20: 
            { TokenList.add(CreateTokenLog(true,yytext(),yyline,yycolumn,"MULTILINE_COMMENT_ERROR_MISSING *\\"));errorCounter+=1;
            }
          case 70: break;
          case 21: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,yytext()));
							return new Symbol(sym.logic,yycolumn,yyline,yytext());
            }
          case 71: break;
          case 22: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"DOUBLE"));
							return new Symbol(sym.DOUBLECONSTANT,yycolumn,yyline,yytext());
            }
          case 72: break;
          case 23: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"STRING"));
							return new Symbol(sym.STRINGCONSTANT,yycolumn,yyline,yytext());
            }
          case 73: break;
          case 24: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"if"));
						return new Symbol(sym.IF,yycolumn,yyline,yytext());
            }
          case 74: break;
          case 25: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"[]"));
						return new Symbol(sym.brackets,yycolumn,yyline,yytext());
            }
          case 75: break;
          case 26: 
            { /*TokenList.add(CreateTokenLog(false,yytext(),yyline,yycolumn,"NORMAL_COMMENT"));*/
            }
          case 76: break;
          case 27: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"int"));
						return new Symbol(sym.INT,yycolumn,yyline,yytext());
            }
          case 77: break;
          case 28: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"New"));
						return new Symbol(sym.New,yycolumn,yyline,yytext());
            }
          case 78: break;
          case 29: 
            { /*TokenList.add(CreateTokenLog(false,yytext(),yyline,yycolumn,"MULTILINE_COMMENT"));*/
            }
          case 79: break;
          case 30: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"BOOLEAN"));
							return new Symbol(sym.BOOLEANCONSTANT,yycolumn,yyline,yytext());
            }
          case 80: break;
          case 31: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"this"));
						return new Symbol(sym.THIS,yycolumn,yyline,yytext());
            }
          case 81: break;
          case 32: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"else"));
						return new Symbol(sym.else_t,yycolumn,yyline,yytext());
            }
          case 82: break;
          case 33: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"null"));
						return new Symbol(sym.NULL,yycolumn,yyline,yytext());
            }
          case 83: break;
          case 34: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"void"));
						return new Symbol(sym.VOID,yycolumn,yyline,yytext());
            }
          case 84: break;
          case 35: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"bool"));
						return new Symbol(sym.BOOL,yycolumn,yyline,yytext());
            }
          case 85: break;
          case 36: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"break"));
						return new Symbol(sym.BREAK,yycolumn,yyline,yytext());
            }
          case 86: break;
          case 37: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"class"));
						return new Symbol(sym.CLASS,yycolumn,yyline,yytext());
            }
          case 87: break;
          case 38: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"while"));
						return new Symbol(sym.WHILE,yycolumn,yyline,yytext());
            }
          case 88: break;
          case 39: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"Print"));
						return new Symbol(sym.Print,yycolumn,yyline,yytext());
            }
          case 89: break;
          case 40: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"return"));
						return new Symbol(sym.RETURN,yycolumn,yyline,yytext());
            }
          case 90: break;
          case 41: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"string"));
						return new Symbol(sym.STRING,yycolumn,yyline,yytext());
            }
          case 91: break;
          case 42: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"double"));
						return new Symbol(sym.DOUBLE,yycolumn,yyline,yytext());
            }
          case 92: break;
          case 43: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"Malloc"));
						return new Symbol(sym.Malloc,yycolumn,yyline,yytext());
            }
          case 93: break;
          case 44: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"extends"));
						return new Symbol(sym.extends_t,yycolumn,yyline,yytext());
            }
          case 94: break;
          case 45: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"getByte"));
						return new Symbol(sym.getByte,yycolumn,yyline,yytext());
            }
          case 95: break;
          case 46: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"NewArray"));
						return new Symbol(sym.NewArray,yycolumn,yyline,yytext());
            }
          case 96: break;
          case 47: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"ReadLine"));
						return new Symbol(sym.ReadLine,yycolumn,yyline,yytext());
            }
          case 97: break;
          case 48: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"interface"));
						return new Symbol(sym.interface_t,yycolumn,yyline,yytext());
            }
          case 98: break;
          case 49: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"implements"));
						return new Symbol(sym.implements_t,yycolumn,yyline,yytext());
            }
          case 99: break;
          case 50: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"ReadInteger"));
						return new Symbol(sym.ReadInteger,yycolumn,yyline,yytext());
            }
          case 100: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
