/* The following code was generated by JFlex 1.6.1 */

//packages
package minicsharp;
import java.util.ArrayList;
import java.io.FileWriter;
import java.io.IOException;
import java_cup.runtime.Symbol;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>miniCsharp.jflex</tt>
 */
public class Analyzer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\40\1\34\1\36\1\36\1\36\22\0\1\40\1\3\1\33"+
    "\2\0\1\7\1\10\1\0\1\72\1\73\1\5\1\4\1\100\1\12"+
    "\1\31\1\6\1\25\7\14\2\14\1\0\1\71\1\1\1\2\1\1"+
    "\2\0\1\57\1\67\2\30\1\32\1\30\1\66\1\13\1\63\2\13"+
    "\1\64\1\65\1\56\1\13\1\61\1\13\1\62\1\70\4\13\1\27"+
    "\2\13\1\74\1\35\1\75\1\0\1\13\1\0\1\22\1\50\1\52"+
    "\1\45\1\20\1\21\1\51\1\53\1\41\1\13\1\55\1\23\1\42"+
    "\1\44\1\47\1\43\1\13\1\16\1\24\1\15\1\17\1\46\1\54"+
    "\1\26\1\60\1\13\1\76\1\11\1\77\1\0\6\13\1\37\32\13"+
    "\1\13\137\13\u1580\0\1\40\u097f\0\13\40\35\0\1\36\1\36\5\0"+
    "\1\40\57\0\1\40\u0fa0\0\1\40\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\ud00f\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\3\5\1\1\1\6"+
    "\1\7\1\10\1\11\5\10\1\11\1\12\1\1\1\13"+
    "\1\6\15\10\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\2\1\3\1\24\1\25\1\26\1\27"+
    "\10\10\2\0\1\30\1\0\1\31\17\10\1\32\1\24"+
    "\2\0\4\27\6\10\1\33\1\10\1\11\1\30\1\10"+
    "\1\34\7\10\1\35\5\10\1\24\1\25\2\0\1\27"+
    "\1\0\1\36\1\37\1\10\1\40\4\10\1\41\1\10"+
    "\1\42\1\10\1\43\10\10\1\25\1\0\1\27\6\10"+
    "\1\44\1\45\1\46\1\10\1\47\5\10\1\24\2\27"+
    "\1\50\1\10\1\51\2\10\1\52\3\10\1\53\2\10"+
    "\1\24\2\0\1\27\1\54\5\10\1\55\1\56\2\10"+
    "\1\57\1\10\1\60\1\10\1\61\1\10\1\62\1\10"+
    "\1\63";

  private static int [] zzUnpackAction() {
    int [] result = new int[195];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\101\0\202\0\202\0\202\0\303\0\u0104\0\101"+
    "\0\u0145\0\u0186\0\303\0\u01c7\0\u0208\0\u0249\0\u028a\0\u02cb"+
    "\0\u030c\0\u034d\0\u038e\0\101\0\u03cf\0\101\0\101\0\u0410"+
    "\0\u0451\0\u0492\0\u04d3\0\u0514\0\u0555\0\u0596\0\u05d7\0\u0618"+
    "\0\u0659\0\u069a\0\u06db\0\u071c\0\101\0\101\0\101\0\u075d"+
    "\0\101\0\101\0\101\0\101\0\101\0\101\0\u079e\0\u07df"+
    "\0\101\0\u0820\0\u0861\0\u08a2\0\u08e3\0\u0924\0\u0965\0\u09a6"+
    "\0\u09e7\0\u0a28\0\u0a69\0\u03cf\0\101\0\u0aaa\0\u01c7\0\u0aeb"+
    "\0\u0b2c\0\u0b6d\0\u0bae\0\u0bef\0\u0c30\0\u0c71\0\u0cb2\0\u0cf3"+
    "\0\u0d34\0\u0d75\0\u0db6\0\u0df7\0\u0e38\0\u0e79\0\101\0\u0eba"+
    "\0\u0efb\0\u0f3c\0\u0f7d\0\u0fbe\0\u0fff\0\u1040\0\u1081\0\u10c2"+
    "\0\u1103\0\u1144\0\u1185\0\u11c6\0\u01c7\0\u1207\0\u0a69\0\u03cf"+
    "\0\u1248\0\u1289\0\u12ca\0\u130b\0\u134c\0\u138d\0\u13ce\0\u140f"+
    "\0\u1450\0\u1491\0\u14d2\0\u1513\0\u1554\0\u1595\0\u15d6\0\u1617"+
    "\0\101\0\u1658\0\u1699\0\u16da\0\u171b\0\u01c7\0\u01c7\0\u175c"+
    "\0\u01c7\0\u179d\0\u17de\0\u181f\0\u1860\0\u01c7\0\u18a1\0\u01c7"+
    "\0\u18e2\0\u01c7\0\u1923\0\u1964\0\u19a5\0\u19e6\0\u1a27\0\u1a68"+
    "\0\u1aa9\0\u1aea\0\u1b2b\0\u1b6c\0\u1bad\0\u1bee\0\u1c2f\0\u1c70"+
    "\0\u1cb1\0\u1cf2\0\u1d33\0\u01c7\0\u01c7\0\u01c7\0\u1d74\0\u01c7"+
    "\0\u1db5\0\u1df6\0\u1e37\0\u1e78\0\u1eb9\0\u1efa\0\u1f3b\0\u1f7c"+
    "\0\u01c7\0\u1fbd\0\u01c7\0\u1ffe\0\u203f\0\u01c7\0\u2080\0\u20c1"+
    "\0\u2102\0\u01c7\0\u2143\0\u2184\0\u21c5\0\u2206\0\u1b2b\0\u2247"+
    "\0\u01c7\0\u2288\0\u22c9\0\u230a\0\u234b\0\u238c\0\u01c7\0\u01c7"+
    "\0\u23cd\0\u240e\0\u01c7\0\u244f\0\u01c7\0\u2490\0\u01c7\0\u24d1"+
    "\0\u01c7\0\u2512\0\u01c7";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[195];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\2\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\14\1\20"+
    "\1\21\2\14\1\22\1\23\3\14\1\24\1\14\1\25"+
    "\1\26\1\2\1\27\1\14\1\27\1\30\2\14\1\31"+
    "\1\32\1\33\1\14\1\34\1\14\1\35\1\14\1\36"+
    "\1\14\1\37\2\14\1\40\1\41\2\14\1\42\1\43"+
    "\1\14\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\103\0\1\55\100\0\1\56\103\0\1\57"+
    "\1\60\102\0\1\61\101\0\1\61\102\0\16\14\1\0"+
    "\1\14\4\0\1\14\1\0\30\14\24\0\1\15\10\0"+
    "\1\15\3\0\1\62\62\0\3\14\1\63\12\14\1\0"+
    "\1\14\4\0\1\14\1\0\12\14\1\64\15\14\23\0"+
    "\5\14\1\65\10\14\1\0\1\14\4\0\1\14\1\0"+
    "\30\14\23\0\10\14\1\66\2\14\1\67\2\14\1\0"+
    "\1\14\4\0\1\14\1\0\30\14\23\0\7\14\1\70"+
    "\6\14\1\0\1\14\4\0\1\14\1\0\6\14\1\71"+
    "\21\14\23\0\2\14\1\72\13\14\1\0\1\14\4\0"+
    "\1\14\1\0\30\14\24\0\1\15\10\0\1\15\2\73"+
    "\1\0\1\62\47\0\33\74\1\75\1\0\1\76\43\74"+
    "\13\0\6\14\1\77\7\14\1\0\1\14\4\0\1\14"+
    "\1\0\1\14\1\100\1\14\1\101\24\14\23\0\4\14"+
    "\1\102\11\14\1\0\1\14\4\0\1\14\1\0\30\14"+
    "\23\0\16\14\1\0\1\14\4\0\1\14\1\0\6\14"+
    "\1\103\21\14\23\0\16\14\1\0\1\14\4\0\1\14"+
    "\1\0\6\14\1\104\21\14\23\0\3\14\1\105\12\14"+
    "\1\0\1\14\4\0\1\14\1\0\6\14\1\106\21\14"+
    "\23\0\10\14\1\107\5\14\1\0\1\14\4\0\1\14"+
    "\1\0\30\14\23\0\16\14\1\0\1\14\4\0\1\14"+
    "\1\0\12\14\1\110\15\14\23\0\5\14\1\111\10\14"+
    "\1\0\1\14\4\0\1\14\1\0\30\14\23\0\3\14"+
    "\1\112\12\14\1\0\1\14\4\0\1\14\1\0\30\14"+
    "\23\0\5\14\1\113\10\14\1\0\1\14\4\0\1\14"+
    "\1\0\30\14\23\0\7\14\1\114\6\14\1\0\1\14"+
    "\4\0\1\14\1\0\30\14\23\0\5\14\1\115\10\14"+
    "\1\0\1\14\4\0\1\14\1\0\30\14\23\0\5\14"+
    "\1\116\10\14\1\0\1\14\4\0\1\14\1\0\30\14"+
    "\105\0\1\117\3\0\5\120\1\121\1\122\72\120\34\60"+
    "\1\0\1\60\2\0\41\60\4\0\1\123\5\0\1\123"+
    "\1\0\1\62\3\0\1\124\4\0\1\125\3\0\1\126"+
    "\1\124\61\0\4\14\1\127\11\14\1\0\1\14\4\0"+
    "\1\14\1\0\30\14\23\0\16\14\1\0\1\14\4\0"+
    "\1\14\1\0\1\130\27\14\23\0\2\14\1\131\13\14"+
    "\1\0\1\14\4\0\1\14\1\0\30\14\23\0\11\14"+
    "\1\132\4\14\1\0\1\14\4\0\1\14\1\0\30\14"+
    "\23\0\2\14\1\133\13\14\1\0\1\14\4\0\1\14"+
    "\1\0\30\14\23\0\10\14\1\134\5\14\1\0\1\14"+
    "\4\0\1\14\1\0\30\14\23\0\3\14\1\135\12\14"+
    "\1\0\1\14\4\0\1\14\1\0\30\14\23\0\3\14"+
    "\1\136\12\14\1\0\1\14\4\0\1\14\1\0\30\14"+
    "\24\0\1\137\3\0\3\137\2\0\1\137\2\0\1\137"+
    "\1\0\1\137\12\0\1\137\2\0\1\137\1\0\1\137"+
    "\4\0\1\137\7\0\1\137\11\0\33\74\1\140\1\0"+
    "\1\76\43\74\13\0\16\14\1\0\1\14\4\0\1\14"+
    "\1\0\2\14\1\141\25\14\23\0\2\14\1\142\13\14"+
    "\1\0\1\14\4\0\1\14\1\0\30\14\23\0\10\14"+
    "\1\143\5\14\1\0\1\14\4\0\1\14\1\0\30\14"+
    "\23\0\4\14\1\144\11\14\1\0\1\14\4\0\1\14"+
    "\1\0\30\14\23\0\16\14\1\0\1\14\4\0\1\14"+
    "\1\0\1\145\27\14\23\0\5\14\1\146\10\14\1\0"+
    "\1\14\4\0\1\14\1\0\30\14\23\0\16\14\1\0"+
    "\1\14\4\0\1\14\1\0\6\14\1\147\21\14\23\0"+
    "\7\14\1\150\6\14\1\0\1\14\4\0\1\14\1\0"+
    "\30\14\23\0\16\14\1\0\1\14\4\0\1\14\1\0"+
    "\1\151\27\14\23\0\16\14\1\0\1\14\4\0\1\14"+
    "\1\0\13\14\1\152\14\14\23\0\16\14\1\0\1\14"+
    "\4\0\1\14\1\0\1\153\27\14\23\0\7\14\1\154"+
    "\6\14\1\0\1\14\4\0\1\14\1\0\30\14\23\0"+
    "\10\14\1\155\5\14\1\0\1\14\4\0\1\14\1\0"+
    "\30\14\23\0\2\14\1\156\13\14\1\0\1\14\4\0"+
    "\1\14\1\0\30\14\23\0\2\14\1\157\13\14\1\0"+
    "\1\14\4\0\1\14\1\0\30\14\10\0\5\120\1\121"+
    "\73\120\5\57\1\160\1\161\72\57\5\162\1\163\1\57"+
    "\72\162\14\0\1\123\10\0\1\164\3\0\1\126\53\0"+
    "\1\123\5\0\1\123\1\0\1\123\10\0\1\164\3\0"+
    "\1\126\53\0\1\123\5\0\1\123\1\0\1\62\3\0"+
    "\1\124\4\0\1\125\2\165\1\0\1\126\1\124\62\0"+
    "\1\126\10\0\1\126\66\0\5\14\1\166\10\14\1\0"+
    "\1\14\4\0\1\14\1\0\30\14\23\0\11\14\1\167"+
    "\4\14\1\0\1\14\4\0\1\14\1\0\30\14\23\0"+
    "\4\14\1\170\11\14\1\0\1\14\4\0\1\14\1\0"+
    "\30\14\23\0\5\14\1\171\10\14\1\0\1\14\4\0"+
    "\1\14\1\0\30\14\23\0\5\14\1\172\10\14\1\0"+
    "\1\14\4\0\1\14\1\0\30\14\23\0\11\14\1\127"+
    "\4\14\1\0\1\14\4\0\1\14\1\0\30\14\23\0"+
    "\16\14\1\0\1\14\4\0\1\14\1\0\1\173\27\14"+
    "\23\0\10\14\1\174\5\14\1\0\1\14\4\0\1\14"+
    "\1\0\30\14\23\0\5\14\1\175\10\14\1\0\1\14"+
    "\4\0\1\14\1\0\30\14\23\0\10\14\1\176\5\14"+
    "\1\0\1\14\4\0\1\14\1\0\30\14\23\0\16\14"+
    "\1\0\1\14\4\0\1\14\1\0\7\14\1\177\20\14"+
    "\23\0\16\14\1\0\1\14\4\0\1\14\1\0\4\14"+
    "\1\200\23\14\23\0\7\14\1\201\6\14\1\0\1\14"+
    "\4\0\1\14\1\0\30\14\23\0\10\14\1\202\5\14"+
    "\1\0\1\14\4\0\1\14\1\0\30\14\23\0\11\14"+
    "\1\203\4\14\1\0\1\14\4\0\1\14\1\0\30\14"+
    "\23\0\10\14\1\204\5\14\1\0\1\14\4\0\1\14"+
    "\1\0\30\14\23\0\16\14\1\0\1\14\4\0\1\14"+
    "\1\0\16\14\1\205\11\14\23\0\16\14\1\0\1\14"+
    "\4\0\1\14\1\0\3\14\1\206\24\14\23\0\16\14"+
    "\1\0\1\14\4\0\1\14\1\0\4\14\1\207\23\14"+
    "\23\0\10\14\1\210\5\14\1\0\1\14\4\0\1\14"+
    "\1\0\30\14\23\0\16\14\1\0\1\14\4\0\1\14"+
    "\1\0\26\14\1\211\1\14\23\0\16\14\1\0\1\14"+
    "\4\0\1\14\1\0\26\14\1\212\1\14\10\0\5\120"+
    "\1\121\1\213\72\120\5\162\1\163\100\162\1\163\1\161"+
    "\72\162\14\0\1\123\10\0\1\164\2\214\1\0\1\126"+
    "\63\0\1\215\3\0\3\215\2\0\1\215\2\0\1\215"+
    "\1\0\1\215\12\0\1\215\2\0\1\215\1\0\1\215"+
    "\4\0\1\215\7\0\1\215\24\0\3\14\1\216\12\14"+
    "\1\0\1\14\4\0\1\14\1\0\30\14\23\0\16\14"+
    "\1\0\1\14\4\0\1\14\1\0\3\14\1\217\24\14"+
    "\23\0\16\14\1\0\1\14\4\0\1\14\1\0\3\14"+
    "\1\220\24\14\23\0\5\14\1\221\10\14\1\0\1\14"+
    "\4\0\1\14\1\0\30\14\23\0\3\14\1\222\12\14"+
    "\1\0\1\14\4\0\1\14\1\0\30\14\23\0\10\14"+
    "\1\223\5\14\1\0\1\14\4\0\1\14\1\0\30\14"+
    "\23\0\16\14\1\0\1\14\4\0\1\14\1\0\14\14"+
    "\1\224\13\14\23\0\11\14\1\225\4\14\1\0\1\14"+
    "\4\0\1\14\1\0\30\14\23\0\5\14\1\226\10\14"+
    "\1\0\1\14\4\0\1\14\1\0\30\14\23\0\3\14"+
    "\1\227\12\14\1\0\1\14\4\0\1\14\1\0\30\14"+
    "\23\0\2\14\1\230\13\14\1\0\1\14\4\0\1\14"+
    "\1\0\30\14\23\0\16\14\1\0\1\14\4\0\1\14"+
    "\1\0\22\14\1\231\1\232\4\14\23\0\16\14\1\0"+
    "\1\14\4\0\1\14\1\0\6\14\1\233\21\14\23\0"+
    "\16\14\1\0\1\14\4\0\1\14\1\0\17\14\1\234"+
    "\10\14\23\0\16\14\1\0\1\14\4\0\1\14\1\0"+
    "\17\14\1\235\10\14\16\0\1\236\106\0\1\237\3\0"+
    "\3\237\2\0\1\237\2\0\1\237\1\0\1\237\12\0"+
    "\1\237\2\0\1\237\1\0\1\237\4\0\1\237\7\0"+
    "\1\237\15\0\1\123\5\0\1\123\1\0\1\215\3\0"+
    "\3\215\2\0\1\240\2\0\1\215\1\126\1\215\12\0"+
    "\1\215\2\0\1\215\1\0\1\215\4\0\1\215\7\0"+
    "\1\215\24\0\16\14\1\0\1\14\4\0\1\14\1\0"+
    "\3\14\1\241\24\14\23\0\16\14\1\0\1\14\4\0"+
    "\1\14\1\0\4\14\1\242\23\14\23\0\16\14\1\0"+
    "\1\14\4\0\1\14\1\0\10\14\1\243\17\14\23\0"+
    "\16\14\1\0\1\14\4\0\1\14\1\0\1\14\1\244"+
    "\26\14\23\0\6\14\1\245\7\14\1\0\1\14\4\0"+
    "\1\14\1\0\30\14\23\0\5\14\1\246\10\14\1\0"+
    "\1\14\4\0\1\14\1\0\30\14\23\0\3\14\1\247"+
    "\12\14\1\0\1\14\4\0\1\14\1\0\30\14\23\0"+
    "\16\14\1\0\1\14\4\0\1\14\1\0\3\14\1\250"+
    "\24\14\23\0\16\14\1\0\1\14\4\0\1\14\1\0"+
    "\1\251\27\14\23\0\16\14\1\0\1\14\4\0\1\14"+
    "\1\0\11\14\1\252\16\14\23\0\2\14\1\253\13\14"+
    "\1\0\1\14\4\0\1\14\1\0\30\14\23\0\2\14"+
    "\1\254\13\14\1\0\1\14\4\0\1\14\1\0\30\14"+
    "\10\0\5\255\1\256\1\257\72\255\14\0\1\237\3\0"+
    "\3\237\2\0\1\260\2\0\1\237\1\126\1\237\12\0"+
    "\1\237\2\0\1\237\1\0\1\237\4\0\1\237\7\0"+
    "\1\237\15\0\1\123\5\0\1\123\1\0\1\215\3\0"+
    "\3\215\2\0\1\240\2\165\1\215\1\126\1\215\12\0"+
    "\1\215\2\0\1\215\1\0\1\215\4\0\1\215\7\0"+
    "\1\215\24\0\11\14\1\261\4\14\1\0\1\14\4\0"+
    "\1\14\1\0\30\14\23\0\5\14\1\262\10\14\1\0"+
    "\1\14\4\0\1\14\1\0\30\14\23\0\7\14\1\263"+
    "\6\14\1\0\1\14\4\0\1\14\1\0\30\14\23\0"+
    "\7\14\1\264\6\14\1\0\1\14\4\0\1\14\1\0"+
    "\30\14\23\0\2\14\1\265\13\14\1\0\1\14\4\0"+
    "\1\14\1\0\30\14\23\0\16\14\1\0\1\14\4\0"+
    "\1\14\1\0\3\14\1\266\24\14\23\0\5\14\1\267"+
    "\10\14\1\0\1\14\4\0\1\14\1\0\30\14\23\0"+
    "\5\14\1\270\10\14\1\0\1\14\4\0\1\14\1\0"+
    "\30\14\10\0\5\255\1\256\73\255\6\236\1\0\72\236"+
    "\14\0\1\237\3\0\3\237\2\0\1\260\2\214\1\237"+
    "\1\126\1\237\12\0\1\237\2\0\1\237\1\0\1\237"+
    "\4\0\1\237\7\0\1\237\24\0\16\14\1\0\1\14"+
    "\4\0\1\14\1\0\3\14\1\271\24\14\23\0\16\14"+
    "\1\0\1\14\4\0\1\14\1\0\11\14\1\272\16\14"+
    "\23\0\16\14\1\0\1\14\4\0\1\14\1\0\17\14"+
    "\1\273\10\14\23\0\5\14\1\274\10\14\1\0\1\14"+
    "\4\0\1\14\1\0\30\14\23\0\5\14\1\275\10\14"+
    "\1\0\1\14\4\0\1\14\1\0\30\14\23\0\2\14"+
    "\1\276\13\14\1\0\1\14\4\0\1\14\1\0\30\14"+
    "\23\0\5\14\1\277\10\14\1\0\1\14\4\0\1\14"+
    "\1\0\30\14\23\0\16\14\1\0\1\14\4\0\1\14"+
    "\1\0\10\14\1\300\17\14\23\0\11\14\1\301\4\14"+
    "\1\0\1\14\4\0\1\14\1\0\30\14\23\0\5\14"+
    "\1\302\10\14\1\0\1\14\4\0\1\14\1\0\30\14"+
    "\23\0\3\14\1\303\12\14\1\0\1\14\4\0\1\14"+
    "\1\0\30\14\10\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9555];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\1\11\13\1\1\11\1\1\2\11"+
    "\15\1\3\11\1\1\6\11\2\1\1\11\11\1\2\0"+
    "\1\11\1\0\20\1\1\11\1\1\2\0\36\1\1\11"+
    "\2\0\1\1\1\0\26\1\1\0\41\1\2\0\24\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[195];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
//Developer´s extra code declaration
private Symbol symbol(int type){
	return new Symbol(type,yyline,yycolumn,yytext());
}

private Symbol symbol(int type,Object value){
	return new Symbol(type,yyline,yycolumn,value	);
}
private static int errorCounter=0;
public   boolean commentError=false;
class token{
	public String content="";
	public int line=0;
	public int column=0;
	public token(String aContent,int aLine,int aColumn){
			content=aContent;
			line=aLine;
			column=aColumn;
	}
}
class Yytoken{
		public Yytoken(){

		}
	}
public static ArrayList<String>TokenList=new ArrayList<String>();
private static String  addsTabs(int tokenLength){
	String tabs="";
	for(int i=32-tokenLength;i>0;i--){
		tabs+=" ";
	}
	return tabs;

}
public static String CreateTokenLog(Boolean isError,String token, int lineNumber,int columnNumber,String description){
	String newToken=token+addsTabs(token.length())+"\t\tLine Number: "+(lineNumber+1)+"\t"+"Column Number: "+(columnNumber)+" To: "+getLastColumn(columnNumber,token.length())+"\tToken Type: "+description+" Token: "+token+"\n";

	String ErrorToken=token+addsTabs(token.length())+"\t\tError at line: "+(lineNumber+1)+"\tDescription: "+description+"\n";

	return isError?ErrorToken:newToken;
}
public static int getLastColumn(int firstColumns,int tokenLength){
	return firstColumns+tokenLength;
}
public static void CreateOutputFile(String outputPath) throws IOException{
	FileWriter writer = null; 
      try {
          writer = new FileWriter(outputPath);
      } catch (IOException ex) {
          System.out.println("Something wrong happened with the output file...");
      }
for(String str: TokenList) {
  writer.write(str);
}
writer.close();
System.out.println("Done!");
if(errorCounter==0){
	System.out.println("The file contains no errors, This file is a cs file");
}
else{
	System.out.println("The file contains "+errorCounter+" errors, This is not a cs file");
}
}




  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Analyzer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 244) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { TokenList.add(CreateTokenLog(true,yytext(),yyline,yycolumn,"UNRECOGNIZED CHARACTER")); errorCounter+=1;
				System.out.println("Caracter no reconocido en la linea: "+yyline+" columna: "+yycolumn+" caracter: "+yytext());
            }
          case 52: break;
          case 2: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,yytext()));
							return new Symbol(sym.comp,yycolumn,yyline,yytext());
            }
          case 53: break;
          case 3: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"="));
							return new Symbol(sym.equal,yycolumn,yyline,yytext());
            }
          case 54: break;
          case 4: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"!"));
							return new Symbol(sym.exclamation,yycolumn,yyline,yytext());
            }
          case 55: break;
          case 5: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,yytext()));
							return new Symbol(sym.arit,yycolumn,yyline,yytext());
            }
          case 56: break;
          case 6: 
            { /*TokenList.add(CreateTokenLog(false,yytext(),yyline,yycolumn,"WHITE_SPACE"));*/
            }
          case 57: break;
          case 7: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,yytext()));
							return new Symbol(sym.minus,yycolumn,yyline,yytext());
            }
          case 58: break;
          case 8: 
            { if(yytext().length()>31){
			
							TokenList.add(CreateTokenLog(true,yytext().substring(0,30),yyline,yycolumn,"IDENTIFIER_TO_LONG,_MAX_SIZE_31_CHARACTERS"));
							errorCounter+=1;
						}
						else{
							TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"IDENTIFIER"));
							return new Symbol(sym.IDENT,yycolumn,yyline,"ID");
						}
            }
          case 59: break;
          case 9: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"INTEGER"));
							return new Symbol(sym.INTCONSTANT,yycolumn,yyline,yytext());
            }
          case 60: break;
          case 10: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"."));
						return new Symbol(sym.dot,yycolumn,yyline,yytext());
            }
          case 61: break;
          case 11: 
            { /*Do nothing...*/
            }
          case 62: break;
          case 12: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,";"));
						return new Symbol(sym.semicolon,yycolumn,yyline,yytext());
            }
          case 63: break;
          case 13: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"("));
						return new Symbol(sym.leftparen,yycolumn,yyline,yytext());
            }
          case 64: break;
          case 14: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,")"));
						return new Symbol(sym.rightparen,yycolumn,yyline,yytext());
            }
          case 65: break;
          case 15: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"["));
						return new Symbol(sym.leftsquarebrace,yycolumn,yyline,yytext());
            }
          case 66: break;
          case 16: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"]"));
						return new Symbol(sym.rightsquarebrace,yycolumn,yyline,yytext());
            }
          case 67: break;
          case 17: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"{"));
						return new Symbol(sym.leftbrace,yycolumn,yyline,yytext());
            }
          case 68: break;
          case 18: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"}"));
						return new Symbol(sym.rightbrace,yycolumn,yyline,yytext());
            }
          case 69: break;
          case 19: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,","));
						return new Symbol(sym.comma,yycolumn,yyline,yytext());
            }
          case 70: break;
          case 20: 
            { TokenList.add(CreateTokenLog(true,yytext(),yyline,yycolumn,"MULTILINE_COMMENT_ERROR_MISSING *\\"));errorCounter+=1;
            }
          case 71: break;
          case 21: 
            { 
            }
          case 72: break;
          case 22: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,yytext()));
							return new Symbol(sym.logic,yycolumn,yyline,yytext());
            }
          case 73: break;
          case 23: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"DOUBLE"));
							return new Symbol(sym.DOUBLECONSTANT,yycolumn,yyline,yytext());
            }
          case 74: break;
          case 24: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"STRING"));
							return new Symbol(sym.STRINGCONSTANT,yycolumn,yyline,yytext());
            }
          case 75: break;
          case 25: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"if"));
						return new Symbol(sym.IF,yycolumn,yyline,yytext());
            }
          case 76: break;
          case 26: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"[]"));
						return new Symbol(sym.brackets,yycolumn,yyline,yytext());
            }
          case 77: break;
          case 27: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"for"));
						return new Symbol(sym.FOR,yycolumn,yyline,yytext());
            }
          case 78: break;
          case 28: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"int"));
						return new Symbol(sym.INT,yycolumn,yyline,yytext());
            }
          case 79: break;
          case 29: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"New"));
						return new Symbol(sym.New,yycolumn,yyline,yytext());
            }
          case 80: break;
          case 30: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"BOOLEAN"));
							return new Symbol(sym.BOOLEANCONSTANT,yycolumn,yyline,yytext());
            }
          case 81: break;
          case 31: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"this"));
						return new Symbol(sym.THIS,yycolumn,yyline,yytext());
            }
          case 82: break;
          case 32: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"else"));
						return new Symbol(sym.else_t,yycolumn,yyline,yytext());
            }
          case 83: break;
          case 33: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"null"));
						return new Symbol(sym.NULL,yycolumn,yyline,yytext());
            }
          case 84: break;
          case 34: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"void"));
						return new Symbol(sym.VOID,yycolumn,yyline,yytext());
            }
          case 85: break;
          case 35: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"bool"));
						return new Symbol(sym.BOOL,yycolumn,yyline,yytext());
            }
          case 86: break;
          case 36: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"break"));
						return new Symbol(sym.BREAK,yycolumn,yyline,yytext());
            }
          case 87: break;
          case 37: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"class"));
						return new Symbol(sym.CLASS,yycolumn,yyline,yytext());
            }
          case 88: break;
          case 38: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"while"));
						return new Symbol(sym.WHILE,yycolumn,yyline,yytext());
            }
          case 89: break;
          case 39: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"Print"));
						return new Symbol(sym.Print,yycolumn,yyline,yytext());
            }
          case 90: break;
          case 40: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"return"));
						return new Symbol(sym.RETURN,yycolumn,yyline,yytext());
            }
          case 91: break;
          case 41: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"string"));
						return new Symbol(sym.STRING,yycolumn,yyline,yytext());
            }
          case 92: break;
          case 42: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"double"));
						return new Symbol(sym.DOUBLE,yycolumn,yyline,yytext());
            }
          case 93: break;
          case 43: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"Malloc"));
						return new Symbol(sym.Malloc,yycolumn,yyline,yytext());
            }
          case 94: break;
          case 44: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"extends"));
						return new Symbol(sym.extends_t,yycolumn,yyline,yytext());
            }
          case 95: break;
          case 45: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"getByte"));
						return new Symbol(sym.getByte,yycolumn,yyline,yytext());
            }
          case 96: break;
          case 46: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"setByte"));
						return new Symbol(sym.SetByte,yycolumn,yyline,yytext());
            }
          case 97: break;
          case 47: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"NewArray"));
						return new Symbol(sym.NewArray,yycolumn,yyline,yytext());
            }
          case 98: break;
          case 48: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"ReadLine"));
						return new Symbol(sym.ReadLine,yycolumn,yyline,yytext());
            }
          case 99: break;
          case 49: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"interface"));
						return new Symbol(sym.interface_t,yycolumn,yyline,yytext());
            }
          case 100: break;
          case 50: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"implements"));
						return new Symbol(sym.implements_t,yycolumn,yyline,yytext());
            }
          case 101: break;
          case 51: 
            { TokenList.add(CreateTokenLog(commentError,yytext(),yyline,yycolumn,"ReadInteger"));
						return new Symbol(sym.ReadInteger,yycolumn,yyline,yytext());
            }
          case 102: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
