
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 21 14:16:39 CST 2018
//----------------------------------------------------

package minicsharp;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int comp = 57;
  public static final int T_mul = 36;
  public static final int brackets = 34;
  public static final int T_NOTEQUAL = 42;
  public static final int T_mod = 38;
  public static final int interface_t = 13;
  public static final int minus = 32;
  public static final int DOUBLE = 49;
  public static final int INT = 48;
  public static final int rightsquarebrace = 4;
  public static final int T_const = 43;
  public static final int extends_t = 11;
  public static final int FOR = 17;
  public static final int comma = 56;
  public static final int T_include = 44;
  public static final int numeral = 45;
  public static final int T_AND = 39;
  public static final int BOOL = 50;
  public static final int DOUBLECONSTANT = 53;
  public static final int CLASS = 8;
  public static final int leftbrace = 9;
  public static final int equal = 21;
  public static final int T_plus = 35;
  public static final int ReadLine = 31;
  public static final int IF = 14;
  public static final int T_includepath = 46;
  public static final int rightparen = 6;
  public static final int THIS = 22;
  public static final int INTCONSTANT = 52;
  public static final int EOF = 0;
  public static final int RETURN = 18;
  public static final int ReadInteger = 25;
  public static final int STRINGCONSTANT = 55;
  public static final int error = 1;
  public static final int NULL = 30;
  public static final int IDENT = 47;
  public static final int BREAK = 19;
  public static final int VOID = 7;
  public static final int Print = 20;
  public static final int leftsquarebrace = 3;
  public static final int NewArray = 24;
  public static final int exclamation = 33;
  public static final int implements_t = 12;
  public static final int SetByte = 29;
  public static final int New = 23;
  public static final int T_EQUAL = 41;
  public static final int Malloc = 26;
  public static final int WHILE = 16;
  public static final int BOOLEANCONSTANT = 54;
  public static final int getByte = 28;
  public static final int T_OR = 40;
  public static final int STRING = 51;
  public static final int else_t = 15;
  public static final int leftparen = 5;
  public static final int T_div = 37;
  public static final int semicolon = 2;
  public static final int rightbrace = 10;
  public static final int dot = 27;
}

