
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 10 09:31:30 CST 2018
//----------------------------------------------------

package minicsharp;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int comp = 42;
  public static final int interface_t = 19;
  public static final int arit = 43;
  public static final int minus = 45;
  public static final int DOUBLE = 5;
  public static final int rightsquarebrace = 9;
  public static final int INT = 4;
  public static final int extends_t = 17;
  public static final int FOR = 23;
  public static final int comma = 13;
  public static final int BOOL = 6;
  public static final int DOUBLECONSTANT = 39;
  public static final int CLASS = 14;
  public static final int leftbrace = 15;
  public static final int equal = 27;
  public static final int ReadLine = 37;
  public static final int IF = 20;
  public static final int rightparen = 11;
  public static final int THIS = 28;
  public static final int INTCONSTANT = 38;
  public static final int EOF = 0;
  public static final int RETURN = 24;
  public static final int ReadInteger = 31;
  public static final int STRINGCONSTANT = 41;
  public static final int error = 1;
  public static final int NULL = 36;
  public static final int BREAK = 25;
  public static final int IDENT = 2;
  public static final int VOID = 12;
  public static final int Print = 26;
  public static final int leftsquarebrace = 8;
  public static final int NewArray = 30;
  public static final int exclamation = 46;
  public static final int implements_t = 18;
  public static final int SetByte = 35;
  public static final int New = 29;
  public static final int Malloc = 32;
  public static final int WHILE = 22;
  public static final int logic = 44;
  public static final int BOOLEANCONSTANT = 40;
  public static final int getByte = 34;
  public static final int else_t = 21;
  public static final int STRING = 7;
  public static final int leftparen = 10;
  public static final int semicolon = 3;
  public static final int rightbrace = 16;
  public static final int dot = 33;
}

